<?php

return [
    'users' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
        'suspend',
        'unsuspend',
    ],
    'tenants' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'roles' => [
        'list',
        'create',
        'read',
        'update',
    ],
    'plans' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'subscriptions' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'features' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'setting-definitions' => [
        'list',
        'create',
        'update',
    ],
    'invoices' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'payments' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'announcements' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'coupons' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'tickets' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'api-keys' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
        'restore',
        'force.delete',
    ],
    'modules' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'activity-logs' => [
        'list',
        'read',
    ],
    'audit-logs' => [
        'list',
    ],
    'settings-groups' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'settings' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'email-templates' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'sms-templates' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'notification-templates' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'overage-charges' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'tax-regions' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'tax-rates' => [
        'list',
        'create',
        'read',
        'update',
        'delete',
    ],
    'billing' => [
        'portal',
        'checkout',
        'payment-methods',
        'invoices',
    ],
    'invoice-pdfs' => [
        'download',
        'stream',
        'generate',
    ],
    'exports' => [
        'create',
        'list',
        'download',
    ],
    'admin-audit-logs' => [
        'list',
    ],
];
